"""init: 7 tables

Revision ID: 265ebd4aa3a1
Revises:
Create Date: 2026-07-19 09:17:14.347640

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "265ebd4aa3a1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("asin", sa.String(length=20), nullable=False),
        sa.Column("site", sa.String(length=5), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("current_phase", sa.SmallInteger(), nullable=False),
        sa.Column("phase_message", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("persona_count", sa.Integer(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_phase", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("site IN ('US','UK','DE','JP')", name="chk_tasks_site"),
        sa.CheckConstraint("source IN ('csv','sorftime')", name="chk_tasks_source"),
        sa.CheckConstraint(
            "status IN ('pending','fetching','tagging','analyzing','rendering','done','failed')",
            name="chk_tasks_status",
        ),
        sa.CheckConstraint("progress BETWEEN 0 AND 100", name="chk_tasks_progress"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "uploads",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_name", sa.String(length=500), nullable=False),
        sa.Column("stored_path", sa.String(length=1000), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("storage_backend", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analysis_reports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("insights_md", sa.Text(), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("strategic_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("chart_configs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("html_content", sa.Text(), nullable=True),
        sa.Column("template_name", sa.String(length=50), nullable=False),
        sa.Column("md_word_count", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_reports_task_id"), "analysis_reports", ["task_id"], unique=True
    )
    op.create_table(
        "personas",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("dimension", sa.String(length=50), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_personas_task_id"), "personas", ["task_id"], unique=False)
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.String(length=50), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("helpful_count", sa.Integer(), nullable=False),
        sa.Column("verified_purchase", sa.Boolean(), nullable=False),
        sa.Column("images", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("variant", sa.String(length=200), nullable=True),
        sa.Column("country", sa.String(length=10), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "review_id", name="uq_reviews_task_review"),
    )
    op.create_index(op.f("ix_reviews_task_id"), "reviews", ["task_id"], unique=False)
    op.create_table(
        "golden_samples",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("persona_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=True),
        sa.Column("sentiment_class", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["persona_id"], ["personas.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_golden_samples_persona_id"), "golden_samples", ["persona_id"], unique=False
    )
    op.create_index(op.f("ix_golden_samples_task_id"), "golden_samples", ["task_id"], unique=False)
    op.create_table(
        "tagged_reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("sentiment", sa.String(length=20), nullable=True),
        sa.Column("info_score", sa.SmallInteger(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tagged_reviews_review_id"), "tagged_reviews", ["review_id"], unique=False
    )
    op.create_index(op.f("ix_tagged_reviews_task_id"), "tagged_reviews", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tagged_reviews_task_id"), table_name="tagged_reviews")
    op.drop_index(op.f("ix_tagged_reviews_review_id"), table_name="tagged_reviews")
    op.drop_table("tagged_reviews")
    op.drop_index(op.f("ix_golden_samples_task_id"), table_name="golden_samples")
    op.drop_index(op.f("ix_golden_samples_persona_id"), table_name="golden_samples")
    op.drop_table("golden_samples")
    op.drop_index(op.f("ix_reviews_task_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_personas_task_id"), table_name="personas")
    op.drop_table("personas")
    op.drop_index(op.f("ix_analysis_reports_task_id"), table_name="analysis_reports")
    op.drop_table("analysis_reports")
    op.drop_table("uploads")
    op.drop_table("tasks")
    # ### end Alembic commands ###
