/** 6 套主题 Token 定义 — 从 review-analyzer-skill 模板 CSS 变量提取 */

import type { ThemeDefinition } from "./types";

const premiumGold: ThemeDefinition = {
  id: "premium-gold",
  name: "Premium Gold",
  description: "黑金奢华 · Playfair Display 字体 · 高管汇报",
  tokens: {
    "--font-display": "'Playfair Display', 'Georgia', serif",
    "--font-body": "'Source Sans 3', 'Segoe UI', sans-serif",
    "--font-mono": "'IBM Plex Mono', 'SF Mono', monospace",
    "--bg": "#070707",
    "--surface": "#111111",
    "--surface-elevated": "#1a1816",
    "--surface-recessed": "#0c0b0a",
    "--border": "rgba(255,255,255,0.06)",
    "--border-bright": "rgba(255,255,255,0.12)",
    "--border-accent": "rgba(212,167,58,0.22)",
    "--text": "#ece5d8",
    "--text-dim": "#9a9186",
    "--text-muted": "#6b6560",
    "--accent": "#d4a73a",
    "--accent-bright": "#f0c850",
    "--accent-dim": "rgba(212,167,58,0.07)",
    "--green": "#5f9a4e",
    "--red": "#c94444",
    "--blue": "#6a9bc7",
    "--orange": "#c4883a",
    "--chart-1": "#d4a73a",
    "--chart-2": "#5f9a4e",
    "--chart-3": "#c94444",
    "--chart-4": "#6a9bc7",
    "--chart-5": "#c4883a",
  },
};

const darkTech: ThemeDefinition = {
  id: "dark-tech",
  name: "Dark Tech",
  description: "赛博朋克 · 青色霓虹 · 技术团队",
  tokens: {
    "--font-display": "'JetBrains Mono', 'SF Mono', monospace",
    "--font-body": "'Inter', 'Segoe UI', sans-serif",
    "--font-mono": "'JetBrains Mono', 'SF Mono', monospace",
    "--bg": "#0a0e14",
    "--surface": "#12171f",
    "--surface-elevated": "#1a1f2a",
    "--surface-recessed": "#080b10",
    "--border": "rgba(0,255,255,0.08)",
    "--border-bright": "rgba(0,255,255,0.18)",
    "--border-accent": "rgba(0,255,255,0.25)",
    "--text": "#d4e8e8",
    "--text-dim": "#6b8a8a",
    "--text-muted": "#4a5a5a",
    "--accent": "#00e5ff",
    "--accent-bright": "#66f0ff",
    "--accent-dim": "rgba(0,229,255,0.07)",
    "--green": "#00c853",
    "--red": "#ff3d4f",
    "--blue": "#448aff",
    "--orange": "#ff9100",
    "--chart-1": "#00e5ff",
    "--chart-2": "#00c853",
    "--chart-3": "#ff3d4f",
    "--chart-4": "#448aff",
    "--chart-5": "#ff9100",
  },
};

const linearMinimal: ThemeDefinition = {
  id: "linear-minimal",
  name: "Linear Minimal",
  description: "极简白蓝 · 清透玻璃 · 产品评审",
  tokens: {
    "--font-display": "'Inter', 'Segoe UI', sans-serif",
    "--font-body": "'Inter', 'Segoe UI', sans-serif",
    "--font-mono": "'SF Mono', 'Consolas', monospace",
    "--bg": "#fafafa",
    "--surface": "#ffffff",
    "--surface-elevated": "#f0f0f5",
    "--surface-recessed": "#e8e8ed",
    "--border": "rgba(0,0,0,0.06)",
    "--border-bright": "rgba(0,0,0,0.12)",
    "--border-accent": "rgba(94,106,210,0.2)",
    "--text": "#1a1a2e",
    "--text-dim": "#6b6b80",
    "--text-muted": "#9a9ab0",
    "--accent": "#5e6ad2",
    "--accent-bright": "#7b85e8",
    "--accent-dim": "rgba(94,106,210,0.06)",
    "--green": "#2ea043",
    "--red": "#cf222e",
    "--blue": "#2563eb",
    "--orange": "#d97706",
    "--chart-1": "#5e6ad2",
    "--chart-2": "#2ea043",
    "--chart-3": "#cf222e",
    "--chart-4": "#2563eb",
    "--chart-5": "#d97706",
  },
};

const posthogAnalytics: ThemeDefinition = {
  id: "posthog-analytics",
  name: "PostHog Analytics",
  description: "暖白橙色 · 运营复盘 · 增长分析",
  tokens: {
    "--font-display": "'Inter', 'Segoe UI', sans-serif",
    "--font-body": "'Inter', 'Segoe UI', sans-serif",
    "--font-mono": "'SF Mono', 'Consolas', monospace",
    "--bg": "#fefaf5",
    "--surface": "#ffffff",
    "--surface-elevated": "#fdf3e7",
    "--surface-recessed": "#f5ebe0",
    "--border": "rgba(0,0,0,0.05)",
    "--border-bright": "rgba(0,0,0,0.10)",
    "--border-accent": "rgba(237,137,54,0.2)",
    "--text": "#2d1f0e",
    "--text-dim": "#6b5a45",
    "--text-muted": "#9a8a78",
    "--accent": "#ed8936",
    "--accent-bright": "#f6a85c",
    "--accent-dim": "rgba(237,137,54,0.06)",
    "--green": "#38964b",
    "--red": "#e04141",
    "--blue": "#3b82f6",
    "--orange": "#ed8936",
    "--chart-1": "#ed8936",
    "--chart-2": "#38964b",
    "--chart-3": "#e04141",
    "--chart-4": "#3b82f6",
    "--chart-5": "#8b5cf6",
  },
};

const stripeExecutive: ThemeDefinition = {
  id: "stripe-executive",
  name: "Stripe Executive",
  description: "翡翠绿 · 金融企业风 · 投资决策",
  tokens: {
    "--font-display": "'Inter', 'Georgia', serif",
    "--font-body": "'Inter', 'Segoe UI', sans-serif",
    "--font-mono": "'SF Mono', 'Consolas', monospace",
    "--bg": "#f8fafc",
    "--surface": "#ffffff",
    "--surface-elevated": "#f1f5f9",
    "--surface-recessed": "#e2e8f0",
    "--border": "rgba(0,0,0,0.05)",
    "--border-bright": "rgba(0,0,0,0.10)",
    "--border-accent": "rgba(16,185,129,0.2)",
    "--text": "#0f172a",
    "--text-dim": "#475569",
    "--text-muted": "#94a3b8",
    "--accent": "#10b981",
    "--accent-bright": "#34d399",
    "--accent-dim": "rgba(16,185,129,0.06)",
    "--green": "#10b981",
    "--red": "#ef4444",
    "--blue": "#3b82f6",
    "--orange": "#f59e0b",
    "--chart-1": "#10b981",
    "--chart-2": "#3b82f6",
    "--chart-3": "#ef4444",
    "--chart-4": "#f59e0b",
    "--chart-5": "#8b5cf6",
  },
};

const warmEditorial: ThemeDefinition = {
  id: "warm-editorial",
  name: "Warm Editorial",
  description: "纸色铜色 · 编辑风格 · 品牌报告",
  tokens: {
    "--font-display": "'Lora', 'Georgia', serif",
    "--font-body": "'Merriweather', 'Georgia', serif",
    "--font-mono": "'SF Mono', 'Consolas', monospace",
    "--bg": "#fdfaf5",
    "--surface": "#fffef9",
    "--surface-elevated": "#f8f3e8",
    "--surface-recessed": "#f0ead8",
    "--border": "rgba(0,0,0,0.06)",
    "--border-bright": "rgba(0,0,0,0.12)",
    "--border-accent": "rgba(180,130,80,0.25)",
    "--text": "#2c1810",
    "--text-dim": "#6b4d3a",
    "--text-muted": "#9a8270",
    "--accent": "#b48250",
    "--accent-bright": "#d4a070",
    "--accent-dim": "rgba(180,130,80,0.06)",
    "--green": "#5a8f4a",
    "--red": "#c04040",
    "--blue": "#4a7ab5",
    "--orange": "#c87830",
    "--chart-1": "#b48250",
    "--chart-2": "#5a8f4a",
    "--chart-3": "#c04040",
    "--chart-4": "#4a7ab5",
    "--chart-5": "#c87830",
  },
};

export const themes: Record<string, ThemeDefinition> = {
  "premium-gold": premiumGold,
  "dark-tech": darkTech,
  "linear-minimal": linearMinimal,
  "posthog-analytics": posthogAnalytics,
  "stripe-executive": stripeExecutive,
  "warm-editorial": warmEditorial,
};

export const themeList = Object.values(themes);
